// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnamASXp3Mel5_JJuKjGXrFkOv2hfsvXM',
    appId: '1:647240252195:web:5a901e105d92938c3a2a96',
    messagingSenderId: '647240252195',
    projectId: 'flutterfff-ca482',
    authDomain: 'flutterfff-ca482.firebaseapp.com',
    storageBucket: 'flutterfff-ca482.firebasestorage.app',
    measurementId: 'G-PXZGRQJSF4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB38_28OfSC70u-FH9UVOFzSb8I9_GC8nk',
    appId: '1:647240252195:android:25f58fe49ae804993a2a96',
    messagingSenderId: '647240252195',
    projectId: 'flutterfff-ca482',
    storageBucket: 'flutterfff-ca482.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz1Lf2uFjecxMGDhJNHN3-rJ4B6elNUxM',
    appId: '1:647240252195:ios:80305716a000f6953a2a96',
    messagingSenderId: '647240252195',
    projectId: 'flutterfff-ca482',
    storageBucket: 'flutterfff-ca482.firebasestorage.app',
    iosBundleId: 'com.example.fff',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz1Lf2uFjecxMGDhJNHN3-rJ4B6elNUxM',
    appId: '1:647240252195:ios:80305716a000f6953a2a96',
    messagingSenderId: '647240252195',
    projectId: 'flutterfff-ca482',
    storageBucket: 'flutterfff-ca482.firebasestorage.app',
    iosBundleId: 'com.example.fff',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnamASXp3Mel5_JJuKjGXrFkOv2hfsvXM',
    appId: '1:647240252195:web:fcb9a7f2e1360a0d3a2a96',
    messagingSenderId: '647240252195',
    projectId: 'flutterfff-ca482',
    authDomain: 'flutterfff-ca482.firebaseapp.com',
    storageBucket: 'flutterfff-ca482.firebasestorage.app',
    measurementId: 'G-WHL95XSH36',
  );

}